### ISSUE TITLE
Project TODO

### ISSUE THREAD

**Issue by JesseNoseworthy** [JesseNoseworthy/react_presentation#9]
- [x] Updated "getting started" README
- [x] Include open browser plugin in `package.json` (https://github.com/JesseNoseworthy/react_presentation/pull/10)
- [x] Make a clear distinction between anchors and `<li>`'s (for example, external button CodePen)
- [x] Update presentation content
- [ ] Refine styling
